version: "3.8"

services:
  backend:
    build:
      context: ../BackendServer
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    volumes:
      - uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=3000
      - STORAGE_TYPE=s3
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - CORS_ORIGIN=${CORS_ORIGIN}
    env_file:
      - ../BackendServer/.env.prod
    restart: unless-stopped
    networks:
      - app-network

  webfrontend:
    build:
      context: ../WebFrontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=${API_URL}
      - VITE_API_BASE_URL=${API_BASE_URL}
    env_file:
      - ../WebFrontend/.env.prod
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
      - webfrontend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  uploads:
